# Generated by Django 3.1.2 on 2020-10-03 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('isite', '0003_auto_20201003_1853'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='published_at',
            field=models.DateField(verbose_name='Дата публикации'),
        ),
    ]
