# Generated by Django 3.1.2 on 2020-10-04 11:21

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('isite', '0005_auto_20201003_2251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='text',
            field=tinymce.models.HTMLField(verbose_name='Текст'),
        ),
    ]
