# Generated by Django 3.1.2 on 2020-10-04 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('isite', '0006_auto_20201004_1421'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
