# Generated by Django 3.1.2 on 2020-10-04 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('isite', '0007_post_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
